version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo-cmscart
    volumes:
      - /home/92335667572/data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-cmscart
    ports: ["8082:8081"]
    depends_on: ["mongo"]

